export const ACTION_TYPES = {
  // Async flow
  FETCH_START: 'FETCH_START',
  FETCH_SUCCESS: 'FETCH_SUCCESS',
  FETCH_ERROR: 'FETCH_ERROR',

  // Search and Filters
  SET_SEARCH_QUERY: 'SET_SEARCH_QUERY',
  SET_GENRE_FILTER: 'SET_GENRE_FILTER',
  SET_SORT_BY: 'SET_SORT_BY',
  SET_SORT_ORDER: 'SET_SORT_ORDER',

  // Pagination
  SET_PAGE: 'SET_PAGE',

  // Favorites
  ADD_FAVORITE: 'ADD_FAVORITE',
  REMOVE_FAVORITE: 'REMOVE_FAVORITE',
  LOAD_FAVORITES: 'LOAD_FAVORITES',

  // Tabs
  SET_ACTIVE_TAB: 'SET_ACTIVE_TAB',

  // Details Modal
  OPEN_MODAL: 'OPEN_MODAL',
  CLOSE_MODAL: 'CLOSE_MODAL',
  SET_MODAL_LOADING: 'SET_MODAL_LOADING',
  SET_MODAL_DATA: 'SET_MODAL_DATA',
  SET_MODAL_ERROR: 'SET_MODAL_ERROR',

  // Reset
  RESET_FILTERS: 'RESET_FILTERS',
};
